  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/pet-hospital
      username: root
      password: 12345678
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update



